alchemy_data = {
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "totalTransactions": "316",
    "result": {
        "docs": [
            {
                "id": "MzQ4ODQ1OTgzOHwxNDg0MjU4MzEw",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "W.T. ECKERT \nWECKERT@WDT.NET",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": -0.46943301,
                                    "type": "negative"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T003000"
                            },
                            "title": "Heuvelton camp destroyed by fire",
                            "url": "http://www.watertowndailytimes.com/news05/heuvelton-camp-destroyed-by-fire-20170112&template=mwdt"
                        }
                    }
                },
                "timestamp": 1484258310
            },
            {
                "id": "MzQ4NTA2MDUyNnwxNDg0MjU4MDYw",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "He heard young kids crying for help, but there \u2018was too much fire\u2019 to save them - USweekly",
                            "url": "http://usweekly.com/news/396/43477/He_heard_young_kids_crying_for_help_but_there_%E2%80%98was_too_much_fire%E2%80%99_to_save_them.html"
                        }
                    }
                },
                "timestamp": 1484258060
            },
            {
                "id": "MzQ4NDc1ODI1NnwxNDg0MjU4MDMw",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": -0.537723005,
                                    "type": "negative"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "Flames spew from California fire station while crew is away - USweekly",
                            "url": "http://usweekly.com/news/396/43503/Flames_spew_from_California_fire_station_while_crew_is_away.html"
                        }
                    }
                },
                "timestamp": 1484258030
            },
            {
                "id": "MzQ3NDM4NzczOHwxNDg0MjU3Nzky",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "BRIAN WITTE \nThe Associated Press",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T154200"
                            },
                            "title": "He heard young kids crying for help, but there \u2018was too much fire\u2019 to save them | Bradenton Herald",
                            "url": "http://www.bradenton.com/news/nation-world/national/article126163379.html"
                        }
                    }
                },
                "timestamp": 1484257792
            },
            {
                "id": "MzQ4MTI2NDUxMnwxNDg0MjU3Nzcy",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "BRIAN WITTE \nThe Associated Press",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T154200"
                            },
                            "title": "He heard young kids crying for help, but there \u2018was too much fire\u2019 to save them | The Herald",
                            "url": "http://www.heraldonline.com/news/nation-world/national/article126163379.html"
                        }
                    }
                },
                "timestamp": 1484257772
            },
            {
                "id": "MzQ3ODU2NzA2NHwxNDg0MjU3NzQ1",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "BRIAN WITTE \nThe Associated Press",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T154200"
                            },
                            "title": "He heard young kids crying for help, but there \u2018was too much fire\u2019 to save them | The Telegraph",
                            "url": "http://www.macon.com/news/nation-world/national/article126163379.html"
                        }
                    }
                },
                "timestamp": 1484257745
            },
            {
                "id": "MzQ4MTM5Mzk4N3wxNDg0MjU3NzM5",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "Apartment Blaze Highlights the Need for Cutting-Edge Fire Safety Systems, says Fire Protection Group Inc.",
                            "url": "http://www.itbusinessnet.com/article/Apartment-Blaze-Highlights-the-Need-for-Cutting-Edge-Fire-Safety-Systems-says-Fire-Protection-Group-Inc-4771105"
                        }
                    }
                },
                "timestamp": 1484257739
            },
            {
                "id": "MzQ3NzQ3OTk1N3wxNDg0MjU3NDM1",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "Patrick Semansky",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": -0.314159989,
                                    "type": "negative"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "The Latest: 6 bodies recovered from home destroyed in fire",
                            "url": "http://www.apnewsarchive.com/2017/A-Baltimore-fire-official-says-six-bodies-have-been-recovered-from-a-home-destroyed-in-an-early-morning-blaze/id-c3af949c8f41479b85c03600530b4672"
                        }
                    }
                },
                "timestamp": 1484257435
            },
            {
                "id": "MzQ3MzA4NzA0NHwxNDg0MjU3MTQy",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "Jeff Sovern",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": -0.693993986,
                                    "type": "negative"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "Brianne Gorod Explains Why Trump Can't Fire CFPB Director Cordray on Day One",
                            "url": "http://pubcit.typepad.com/clpblog/2017/01/brianne-gorod-explains-why-trump-cant-fire-cfpb-director-cordray-on-day-one.html"
                        }
                    }
                },
                "timestamp": 1484257142
            },
            {
                "id": "MzQ3MjI2NTQ1MHwxNDg0MjU3MDQ2",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": -0.537723005,
                                    "type": "negative"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T155800"
                            },
                            "title": "Flames spew from California fire station while crew is away",
                            "url": "http://www.whec.com/national/flames-spew-from-california-fire-station-while-crew-is-away/4369342/"
                        }
                    }
                },
                "timestamp": 1484257046
            },
            {
                "id": "MzQ3NDMzOTUzN3wxNDg0MjU3MDEw",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "NBC News",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20160112T000000"
                            },
                            "title": "6 Children Presumed Dead in Baltimore House Fire",
                            "url": "http://www.nbclosangeles.com/multimedia/Baltimore-House-Fire-410556235.html"
                        }
                    }
                },
                "timestamp": 1484257010
            },
            {
                "id": "MzQ3Mjc3MTk0OHwxNDg0MjU2ODI5",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "Annette Arreola",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "Fire Rips Through Buena Park Fire Station",
                            "url": "http://www.nbclosangeles.com/on-air/as-seen-on/Fire-Rips-Through-Buena-Park-Fire-Station_1_Los-Angeles-410527545.html"
                        }
                    }
                },
                "timestamp": 1484256829
            },
            {
                "id": "MzQ3MTIwNjQyMHwxNDg0MjU2NjMx",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "nurun.com",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "Sarnia Fire Department and our taxes. | Entertainment | UR",
                            "url": "http://www.theobserver.ca/ur/story/1220810"
                        }
                    }
                },
                "timestamp": 1484256631
            },
            {
                "id": "MzQ2MTcyOTgxMnwxNDg0MjU2NTAw",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "Texas Teen Calls Mom",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 1,
                                    "score": 0.434691995,
                                    "type": "positive"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "Texas Teen Calls Mom, a 911 Dispatcher, When House Catches Fire",
                            "url": "http://www.nbcmiami.com/news/national-international/Texas-Teen-Calls-Mom-a-911-Dispatcher-When-House-Catches-Fire-410443395.html"
                        }
                    }
                },
                "timestamp": 1484256500
            },
            {
                "id": "MzQ3MDA1MzA2MXwxNDg0MjU2NDk2",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "Jeff Sovern",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": -0.419719011,
                                    "type": "negative"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "House Financial Services Committee Democrats Urge Trump Not to Fire Cordray",
                            "url": "http://pubcit.typepad.com/clpblog/2017/01/house-financial-services-committee-democrats-urge-trump-not-to-fire-cordray.html"
                        }
                    }
                },
                "timestamp": 1484256496
            },
            {
                "id": "MzQ2MTI5OTk2MHwxNDg0MjU2NDQ4",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "NBC News",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20160112T000000"
                            },
                            "title": "6 Children Presumed Dead in Baltimore House Fire",
                            "url": "http://www.nbcdfw.com/multimedia/Baltimore-House-Fire-410556235.html"
                        }
                    }
                },
                "timestamp": 1484256448
            },
            {
                "id": "MzQ2OTMwMzk4OHwxNDg0MjU2NDI5",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "Manx Telecom",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0.775049984,
                                    "type": "positive"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "electric fire and fan heater - manx.net Isle of Man Classifieds",
                            "url": "https://www.manx.net/classifieds/miscellaneous/advert/795629/electric-fire-and-fan-heater"
                        }
                    }
                },
                "timestamp": 1484256429
            },
            {
                "id": "MzQ2NzU4OTIyMXwxNDg0MjU2MjYx",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "Union Leader staff",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "Manchester Fire Department calls West Side fires \u2018suspicious\u2019 | New Hampshire",
                            "url": "http://www.unionleader.com/article/20170112/NEWS07/170119713"
                        }
                    }
                },
                "timestamp": 1484256261
            },
            {
                "id": "MzQ2NDc1NDM4N3wxNDg0MjU2MjA5",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "GOP Bill Makes it Easier For Gov. Agencies to Fire Employees - USweekly",
                            "url": "http://usweekly.com/news/461/845/GOP_Bill_Makes_it_Easier_For_Gov_Agencies_to_Fire_Employees.html"
                        }
                    }
                },
                "timestamp": 1484256209
            },
            {
                "id": "MzQ2NjkzNDc0NnwxNDg0MjU2MTU0",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "Rep. Randy Weber: Fire CNN Reporter Who Interrupted Trump - USweekly",
                            "url": "http://usweekly.com/news/461/847/Rep_Randy_Weber_Fire_CNN_Reporter_Who_Interrupted_Trump.html"
                        }
                    }
                },
                "timestamp": 1484256154
            },
            {
                "id": "MzQ2NTI0NjMzMnwxNDg0MjU2MDAx",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "NBC News",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": 0,
                                    "type": "neutral"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20160112T000000"
                            },
                            "title": "6 Children Presumed Dead in Baltimore House Fire",
                            "url": "http://www.nbcchicago.com/multimedia/Baltimore-House-Fire-410556235.html"
                        }
                    }
                },
                "timestamp": 1484256001
            },
            {
                "id": "MzQ1NTg5Mzg4MXwxNDg0MjU1OTM2",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": -0.537723005,
                                    "type": "negative"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T145400"
                            },
                            "title": "Flames spew from California fire station while crew is away",
                            "url": "http://kstp.com/national/flames-spew-from-california-fire-station-while-crew-is-away/4369335/?cat=162"
                        }
                    }
                },
                "timestamp": 1484255936
            },
            {
                "id": "MzQ2MjcwOTYwOXwxNDg0MjU1Nzkw",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "Associated Press \n January 12",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": -0.537723005,
                                    "type": "negative"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "Flames spew from California fire station while crew is away",
                            "url": "http://www.startribune.com/flames-spew-from-california-fire-station-while-crew-is-away/410560305/"
                        }
                    }
                },
                "timestamp": 1484255790
            },
            {
                "id": "MzQ2MjU5OTIxM3wxNDg0MjU1Nzg2",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "NBC News",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": -0.356445014,
                                    "type": "negative"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20160112T000000"
                            },
                            "title": "5 Children Dead; 1 Presumed Killed in Baltimore House Fire",
                            "url": "http://www.nbcnewyork.com/multimedia/Baltimore-House-Fire-410556235.html"
                        }
                    }
                },
                "timestamp": 1484255786
            },
            {
                "id": "MzQ2MjI2MDQ3MHwxNDg0MjU1NzQx",
                "source": {
                    "enriched": {
                        "url": {
                            "author": "",
                            "enrichedTitle": {
                                "docSentiment": {
                                    "mixed": 0,
                                    "score": -0.537723005,
                                    "type": "negative"
                                }
                            },
                            "publicationDate": {
                                "confident": "no",
                                "date": "20170112T000000"
                            },
                            "title": "Flames spew from California fire station while crew is away",
                            "url": "http://www.greenwichtime.com/news/us/article/Crews-extinguish-blaze-at-Orange-County-fire-10852735.php"
                        }
                    }
                },
                "timestamp": 1484255741
            }
        ],
        "next": "Njk2OTI2NDAxNzIwODM4OTU2N3x8NzYwMDAzODY3OTU2NjA4MjcxN3x8ODYzODI3MDQ1MDkwMjcxNjgzOHx8MTE0ODYxNDkxNzgwODgyNjk2Njl8TXpRMk1qVTVPVEl4TTN3eE5EZzBNalUxTnpnMnwxMzMwNjkyMDk5MDg2NDkwMTkzNXxNelEyTWpJMk1EUTNNSHd4TkRnME1qVTFOelF4fDE1NTI0OTYyMjYwNDk1MDk4MjIwfE16UTJORGMxTkRNNE4zd3hORGcwTWpVMk1qQTV8MTYwNTk1OTA0ODYzMjI0MTk2NTN8TXpRMU5UZzVNemc0TVh3eE5EZzBNalUxT1RNMnwxNzQ3NDYzNTI1MDgxODMxMTgyNXw",
        "status": "OK"
    }
}
